### ISSUE TITLE
Update the template for Athens 3

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/template#12]
```[tasklist]
### Tasks
- [x] Import tasks from `@zetachain/toolkit`
- [x] Import `getHardhatConfigNetworks` from `@zetachain/toolkit`
- [x] Merge the PR into main
```

Related PR: https://github.com/zeta-chain/template/pull/11
